#region Using Directives

using System.Collections.Generic;

#endregion

namespace Pharmatechnik.Nav.Language.CodeGen;

/// <summary>
/// Die geteilten Emitter-Bausteine der CodeBuilder-basierten C#-Erzeugung — das C#-Pendant zu den
/// wiederverwendbaren Templates aus <c>Common.stg</c> (Dateikopf, Using-Direktiven, die Nav-Annotations
/// im generierten Code). Sie schreiben ausschließlich generationsübergreifend Gleiches; das
/// versionierbare bzw. artefakt-spezifische Wissen bleibt beim jeweiligen Emitter.
/// </summary>
static class EmitterCommon {

    /// <summary>Name der Region, die die Nav-Annotations klammert (<c>#region Nav Annotations</c>).</summary>
    const string AnnotationRegionName = "Nav Annotations";

    /// <summary>
    /// Schreibt den <c>&lt;auto-generated&gt;</c>-Dateikopf. Die Kopf-Zeilen sind versionsfrei; bei
    /// aktivem Nullable-Kontext folgt unmittelbar <c>#nullable enable</c>. Die letzte Zeile wird mit
    /// Zeilenumbruch abgeschlossen, sodass der Aufrufer nahtlos weiterschreibt.
    /// </summary>
    public static void WriteFileHeader(CodeBuilder cb, CodeGeneratorContext context) {
        cb.WriteLine("//------------------------------------------------------------------------------");
        cb.WriteLine("// <auto-generated>");
        cb.WriteLine("//     This code was generated by a tool.");
        cb.WriteLine("//");
        cb.WriteLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        cb.WriteLine("//     the code is regenerated.");
        cb.WriteLine("// </auto-generated>");
        cb.Write("//------------------------------------------------------------------------------");

        if (context.NullableContext) {
            cb.WriteLine();
            cb.Write("#nullable enable");
        }

        cb.WriteLine();
    }

    /// <summary>
    /// Schreibt den <c>#region Using Directives</c>-Block mit je einer <c>using</c>-Zeile pro
    /// Namespace, abgeschlossen mit <c>#endregion</c> (samt Zeilenumbruch).
    /// </summary>
    public static void WriteUsingDirectives(CodeBuilder cb, IEnumerable<string> usingNamespaces) {
        cb.WriteLine("#region Using Directives");
        foreach (var ns in usingNamespaces) {
            cb.Write("using ").Write(ns).WriteLine(";");
        }

        cb.WriteLine("#endregion");
    }

    /// <summary>
    /// Schreibt die Task-Annotation (<c>NavFile</c>/<c>NavTask</c>), über die der
    /// <c>AnnotationReader</c> vom generierten Code auf die <c>.nav</c>-Quelle und den Task
    /// zurückfindet.
    /// </summary>
    public static void WriteTaskAnnotation(CodeBuilder cb, string syntaxFileName, string taskName) {
        cb.Write("#region ").WriteLine(AnnotationRegionName);
        cb.Write("/// <").Write(CodeGenInvariants.AnnotationTagNavFile).Write(">")
          .Write(syntaxFileName)
          .Write("</").Write(CodeGenInvariants.AnnotationTagNavFile).WriteLine(">");
        cb.Write("/// <").Write(CodeGenInvariants.AnnotationTagNavTask).Write(">")
          .Write(taskName)
          .Write("</").Write(CodeGenInvariants.AnnotationTagNavTask).WriteLine(">");
        cb.WriteLine("#endregion");
    }

    /// <summary>Schreibt die Init-Annotation (<c>NavInit</c>) einer Begin-Methode.</summary>
    public static void WriteNavInitAnnotation(CodeBuilder cb, string initName) {
        cb.Write("#region ").WriteLine(AnnotationRegionName);
        cb.Write("/// <").Write(CodeGenInvariants.AnnotationTagNavInit).Write(">")
          .Write(initName)
          .Write("</").Write(CodeGenInvariants.AnnotationTagNavInit).WriteLine(">");
        cb.WriteLine("#endregion");
    }

}
