#region Using Directives

using System.Collections.Generic;

#endregion

namespace Pharmatechnik.Nav.Language.CodeGen;

/// <summary>
/// Die geteilten Emitter-Bausteine der CodeBuilder-basierten C#-Erzeugung — das C#-Pendant zu den
/// wiederverwendbaren Templates aus <c>Common.stg</c> (Dateikopf, Using-Direktiven, die Nav-Annotations
/// im generierten Code). Sie schreiben ausschließlich generationsübergreifend Gleiches; das
/// versionierbare bzw. artefakt-spezifische Wissen bleibt beim jeweiligen Emitter.
/// </summary>
static class EmitterCommon {

    /// <summary>Name der Region, die die Nav-Annotations klammert (<c>#region Nav Annotations</c>).</summary>
    const string AnnotationRegionName = "Nav Annotations";

    /// <summary>
    /// Schreibt den <c>&lt;auto-generated&gt;</c>-Dateikopf. Die Kopf-Zeilen sind versionsfrei; bei
    /// aktivem Nullable-Kontext folgt unmittelbar <c>#nullable enable</c>. Die letzte Zeile wird mit
    /// Zeilenumbruch abgeschlossen, sodass der Aufrufer nahtlos weiterschreibt.
    /// </summary>
    public static void WriteFileHeader(CodeBuilder cb, CodeGeneratorContext context) {
        cb.WriteLine("""
                     //------------------------------------------------------------------------------
                     // <auto-generated>
                     //     This code was generated by a tool.
                     //
                     //     Changes to this file may cause incorrect behavior and will be lost if
                     //     the code is regenerated.
                     // </auto-generated>
                     //------------------------------------------------------------------------------
                     """);

        if (context.NullableContext) {
            cb.WriteLine("#nullable enable");
        }
    }

    /// <summary>
    /// Schreibt den <c>#region Using Directives</c>-Block mit je einer <c>using</c>-Zeile pro
    /// Namespace, abgeschlossen mit <c>#endregion</c> (samt Zeilenumbruch).
    /// </summary>
    public static void WriteUsingDirectives(CodeBuilder cb, IEnumerable<string> usingNamespaces) {
        cb.WriteLine("#region Using Directives");
        foreach (var ns in usingNamespaces) {
            cb.WriteLine($"using {ns};");
        }

        cb.WriteLine("#endregion");
    }

    /// <summary>
    /// Schreibt die Task-Annotation (<c>NavFile</c>/<c>NavTask</c>), über die der
    /// <c>AnnotationReader</c> vom generierten Code auf die <c>.nav</c>-Quelle und den Task
    /// zurückfindet.
    /// </summary>
    public static void WriteTaskAnnotation(CodeBuilder cb, string syntaxFileName, string taskName) {
        cb.WriteLine($"""
                      #region {AnnotationRegionName}
                      /// <{CodeGenInvariants.AnnotationTagNavFile}>{syntaxFileName}</{CodeGenInvariants.AnnotationTagNavFile}>
                      /// <{CodeGenInvariants.AnnotationTagNavTask}>{taskName}</{CodeGenInvariants.AnnotationTagNavTask}>
                      #endregion
                      """);
    }

    /// <summary>Schreibt die Init-Annotation (<c>NavInit</c>) einer Begin-Methode.</summary>
    public static void WriteNavInitAnnotation(CodeBuilder cb, string initName) {
        cb.WriteLine($"""
                      #region {AnnotationRegionName}
                      /// <{CodeGenInvariants.AnnotationTagNavInit}>{initName}</{CodeGenInvariants.AnnotationTagNavInit}>
                      #endregion
                      """);
    }

    /// <summary>Schreibt die Trigger-Annotation (<c>NavTrigger</c>) einer Trigger-Methode.</summary>
    public static void WriteTriggerAnnotation(CodeBuilder cb, string triggerName) {
        cb.WriteLine($"""
                      #region {AnnotationRegionName}
                      /// <{CodeGenInvariants.AnnotationTagNavTrigger}>{triggerName}</{CodeGenInvariants.AnnotationTagNavTrigger}>
                      #endregion
                      """);
    }

    /// <summary>Schreibt die Exit-Annotation (<c>NavExit</c>) einer Exit-Methode.</summary>
    public static void WriteNavExitAnnotation(CodeBuilder cb, string nodeName) {
        cb.WriteLine($"""
                      #region {AnnotationRegionName}
                      /// <{CodeGenInvariants.AnnotationTagNavExit}>{nodeName}</{CodeGenInvariants.AnnotationTagNavExit}>
                      #endregion
                      """);
    }

    /// <summary>Schreibt die Init-Call-Annotation (<c>NavInitCall</c>) einer Begin-Wrapper-Methode.</summary>
    public static void WriteInitCallAnnotation(CodeBuilder cb, string beginInterfaceFullyQualifiedName) {
        cb.WriteLine($"""
                      #region {AnnotationRegionName}
                      /// <{CodeGenInvariants.AnnotationTagNavInitCall}>{beginInterfaceFullyQualifiedName}</{CodeGenInvariants.AnnotationTagNavInitCall}>
                      #endregion
                      """);
    }

}
