#region Using Directives

using System;
using System.Collections.Generic;
using System.Linq;

#endregion

namespace Pharmatechnik.Nav.Language.CodeGen;

/// <summary>
/// CodeBuilder-Emitter der <c>{Task}WFS</c>-OneShot-Familie — der technische Ersatz für
/// <c>WFSOneShot.stg</c>. Erzeugt die <b>Benutzer-Datei</b> (<c>{Task}WFS.cs</c>,
/// <see cref="OverwritePolicy.Never"/>): die partielle Implementierungsklasse <c>{Task}WFS</c> mit
/// je einem <c>NotImplementedException</c>-Stub für die abstrakten Init-/Exit-/Trigger-Methoden aus
/// <c>{Task}WFSBase</c>, die der Nutzer ausprogrammiert.
/// </summary>
/// <remarks>
/// Anders als die übrigen Familien schreibt die OneShot-Datei <b>keinen</b>
/// <c>&lt;auto-generated&gt;</c>-Dateikopf — sie ist eine bearbeitbare Benutzer-Datei und beginnt
/// direkt mit den Using-Direktiven. Klassenname und Namespace sind <b>versionierbar</b>
/// (<see cref="ICodeGenFacts"/> via <see cref="TaskCodeInfo"/>); die überschriebenen Methodennamen
/// stammen aus denselben Facts wie in <see cref="WfsBaseEmitter"/>.
/// </remarks>
// ReSharper disable once InconsistentNaming
static class WfsOneShotEmitter {

    public static string Emit(WfsCodeModel model, CodeGeneratorContext context) {

        var cb    = new CodeBuilder();
        var facts = model.Task.Facts;

        // OneShot ist die Benutzer-Datei — kein <auto-generated>-Header (anders als die übrigen Familien).
        EmitterCommon.WriteUsingDirectives(cb, model.UsingNamespaces);

        cb.WriteLine();
        cb.Write($"namespace {model.WflNamespace} ");
        using (cb.Block()) {

            cb.Write($"public partial class {model.WfsTypeName} ");
            using (cb.Block()) {
                WriteMethodStubs(cb, model, facts);
            }
        }

        return cb.ToString();
    }

    // -- Die Methoden-Stubs der Implementierungsklasse ------------------------------------------------

    static void WriteMethodStubs(CodeBuilder cb, WfsCodeModel model, ICodeGenFacts facts) {

        var wroteAny = false;

        void Stub(Action write) {
            // Jede Methode ist von der vorigen durch genau eine Leerzeile getrennt.
            if (wroteAny) {
                cb.WriteLine();
            }

            write();
            // Block() schließt mit '}' ohne Zeilenumbruch — die Stub-Zeile hier abschließen.
            cb.WriteLine();
            wroteAny = true;
        }

        foreach (var initTransition in model.InitTransitions) {
            Stub(() => WriteInitStub(cb, initTransition, facts));
        }

        foreach (var exitTransition in model.ExitTransitions) {
            Stub(() => WriteExitStub(cb, exitTransition, facts));
        }

        foreach (var triggerTransition in model.TriggerTransitions) {
            Stub(() => WriteTriggerStub(cb, triggerTransition, facts));
        }

        // ST-Sektionsstruktur: die Init-/Exit-Sektionen enden im Template mit <\\> + Leerzeile, die
        // Trigger-Sektion nicht. Fehlt die Trigger-Sektion, bleibt deshalb eine strukturelle Leerzeile
        // vor der schließenden Klammer stehen; mit Triggern schließt die letzte Methode direkt an.
        if (model.TriggerTransitions.Count == 0) {
            cb.WriteLine();
        }
    }

    static void WriteInitStub(CodeBuilder cb, InitTransitionCodeModel initTransition, ICodeGenFacts facts) {

        if (initTransition.GenerateAbstractMethod) {
            cb.Write($"public override IINIT_TASK {facts.BeginMethodPrefix}(");
            WriteParameterList(cb, initTransition.Parameter);
        } else {
            cb.Write($"protected override INavCommandBody {facts.BeginMethodPrefix}{facts.LogicMethodSuffix}(");
            WriteParameterList(cb, initTransition.Parameter.Concat(initTransition.TaskBegins));
        }

        WriteNotImplementedBody(cb);
    }

    static void WriteExitStub(CodeBuilder cb, ExitTransitionCodeModel exitTransition, ICodeGenFacts facts) {

        var exitMethod = $"{facts.ExitMethodPrefix}{exitTransition.NodeNamePascalcase}";

        if (exitTransition.GenerateAbstractMethod) {
            cb.Write($"protected override INavCommand {exitMethod}(");
            WriteParameterList(cb, new[] { exitTransition.TaskResult });
        } else {
            cb.Write($"protected override INavCommandBody {exitMethod}{facts.LogicMethodSuffix}(");
            WriteParameterList(cb, new[] { exitTransition.TaskResult }.Concat(exitTransition.TaskBegins));
        }

        WriteNotImplementedBody(cb);
    }

    static void WriteTriggerStub(CodeBuilder cb, TriggerTransitionCodeModel triggerTransition, ICodeGenFacts facts) {

        cb.Write($"protected override INavCommandBody {triggerTransition.TriggerName}{facts.LogicMethodSuffix}(");
        WriteParameterList(cb, new[] { triggerTransition.ViewParameter }.Concat(triggerTransition.TaskBegins));

        WriteNotImplementedBody(cb);
    }

    /// <summary>Schreibt den gemeinsamen Rumpf jeder OneShot-Methode: <c>{ throw new NotImplementedException(); }</c>.</summary>
    static void WriteNotImplementedBody(CodeBuilder cb) {
        cb.Write(") ");
        using (cb.Block()) {
            cb.WriteLine("throw new NotImplementedException();");
        }
    }

    /// <summary>Umbrochene, an der öffnenden Klammer ausgerichtete Parameterliste (<c>{Typ} {Name}</c>).</summary>
    static void WriteParameterList(CodeBuilder cb, IEnumerable<ParameterCodeModel> parameters) {
        cb.WriteAlignedJoin(parameters, p => cb.Write($"{p.ParameterType} {p.ParameterName}"), separator: $",{cb.NewLine}");
    }

}
