#region Using Directives

#endregion

namespace Pharmatechnik.Nav.Language.CodeGen;

/// <summary>
/// CodeBuilder-Emitter der <c>{View}TO</c>-Familie — der technische Ersatz für <c>TO.stg</c>. Erzeugt je
/// referenziertem View-Knoten einen einmaligen Platzhalter <c>partial class {View}TO : TO</c> im
/// IWFL-Namespace des Tasks (<see cref="OverwritePolicy.Never"/>). Der eigentliche TO-Inhalt gehört dem
/// externen GUI-Generator, der diese Datei überschreibt; nav.exe legt nur das Gerüst an.
/// </summary>
/// <remarks>
/// Anders als die übrigen Familien trägt die TO-Datei <b>keinen</b> <c>&lt;auto-generated&gt;</c>-Kopf,
/// sondern den „nur einmalig erzeugt"-Hinweis (siehe <see cref="WriteFileHeader"/>) — er signalisiert,
/// dass die Datei sicher von Hand oder vom GUI-Generator überschrieben werden darf.
/// </remarks>
// ReSharper disable once InconsistentNaming
static class TOEmitter {

    public static string Emit(TOCodeModel model, CodeGeneratorContext context) {

        var cb = new CodeBuilder();

        WriteFileHeader(cb);
        EmitterCommon.WriteUsingDirectives(cb, model.UsingNamespaces);

        cb.WriteLine();
        cb.Write($"namespace {model.IwflNamespace} ");
        using (cb.Block()) {

            cb.Write($"public partial class {model.ClassName} : TO ");
            using (cb.Block()) {
                cb.WriteLine("// Full TO code is generated by the GUI generator which will overwrite this file!");
            }
        }

        return cb.ToString();
    }

    /// <summary>
    /// Schreibt den TO-spezifischen Dateikopf: nicht der <c>&lt;auto-generated&gt;</c>-Kopf, sondern der
    /// „only generated once"-Hinweis der ehemaligen <c>TO.stg</c>.
    /// </summary>
    static void WriteFileHeader(CodeBuilder cb) {
        cb.WriteLine("""
                     //------------------------------------------------------------------------------
                     //     This code was generated by a tool.
                     //
                     //     This file is only generated once.
                     //     It can be overwritten manually or by the GUI generator safely!
                     //------------------------------------------------------------------------------
                     """);
    }

}
