#region Using Directives

using System.Collections.Generic;
using System.Linq;

#endregion

namespace Pharmatechnik.Nav.Language.CodeGen;

/// <summary>
/// CodeBuilder-Emitter der <c>{Task}WFS</c>-OneShot-Familie der <b>Generation 2</b> — die einmalig
/// erzeugte Benutzer-Datei (<see cref="OverwritePolicy.Never"/>) mit je einem
/// <c>NotImplementedException</c>-Stub für die abstrakten Methoden aus <c>{Task}WFSBase</c>.
/// </summary>
/// <remarks>
/// Anders als V1 überschreiben die Stubs die neuen Logic-Signaturen
/// <c>protected override {Context}.Result …Logic(args, {Context} next)</c> (bzw. bei
/// <c>[abstract]</c>-Quellen die Maschinerie-Methode selbst). Wie die V1-OneShot-Datei trägt sie
/// <b>keinen</b> <c>&lt;auto-generated&gt;</c>-Kopf.
/// </remarks>
static class WfsOneShotEmitterV2 {

    /// <summary>
    /// Rendert die einmalige Benutzer-Datei <c>{Task}WFS</c> aus <paramref name="model"/>: <c>using</c>s
    /// (ohne <c>&lt;auto-generated&gt;</c>-Kopf) und im Task-Namespace die partielle Klasse <c>{Task}WFS</c>
    /// mit je einem <c>NotImplementedException</c>-Stub für die abstrakten Logic-/Maschinerie-Methoden.
    /// </summary>
    public static string Emit(WfsCodeModelV2 model, CodeGeneratorContext context) {

        var cb = new CodeBuilder();

        // OneShot ist die Benutzer-Datei — kein <auto-generated>-Header.
        EmitterCommon.WriteUsingDirectives(cb, model.UsingNamespaces);

        EmitterCommon.WriteNamespace(cb, model.WflNamespace);

        cb.Write($"public partial class {model.WfsTypeName} ");
        using (cb.Block()) {
            WriteMethodStubs(cb, model);
        }

        return cb.ToString();
    }

    /// <summary>
    /// Schreibt die Methoden-Stubs — erst je Init-/Exit-/Trigger-Transition (<see cref="WriteStub"/>), dann je
    /// Choice (<see cref="WriteChoiceStub"/>), jeweils durch genau eine Leerzeile getrennt.
    /// </summary>
    static void WriteMethodStubs(CodeBuilder cb, WfsCodeModelV2 model) {

        var transitions = model.InitTransitions
                               .Concat(model.ExitTransitions)
                               .Concat(model.TriggerTransitions)
                               .ToList();

        var wroteAny = false;

        foreach (var transition in transitions) {
            // Jede Methode ist von der vorigen durch genau eine Leerzeile getrennt.
            if (wroteAny) {
                cb.WriteLine();
            }

            WriteStub(cb, transition);
            // Block() schließt mit '}' ohne Zeilenumbruch — die Stub-Zeile hier abschließen.
            cb.WriteLine();
            wroteAny = true;
        }

        // Die {Choice}Logic-Stubs folgen — die Entscheidung, die der Nutzer je Choice EINMAL trifft (§3.5).
        foreach (var choice in model.Choices) {
            if (wroteAny) {
                cb.WriteLine();
            }

            WriteChoiceStub(cb, choice);
            cb.WriteLine();
            wroteAny = true;
        }
    }

    /// <summary>
    /// Schreibt den <c>NotImplementedException</c>-Stub einer Transition: bei
    /// <see cref="TransitionCallContextCodeModel.GenerateAbstractMachinery"/> überschreibt er die
    /// Maschinerie-Methode selbst, sonst die abstrakte <c>…Logic</c>-Methode (inkl. Context-Parameter).
    /// </summary>
    static void WriteStub(CodeBuilder cb, TransitionCallContextCodeModel transition) {

        if (transition.GenerateAbstractMachinery) {
            // [abstract]-Quelle: die Maschinerie-Methode selbst wird überschrieben.
            cb.Write($"{transition.AccessModifier} override {transition.ReturnType} {transition.MachineryName}(");
            WriteAlignedDecls(cb, transition.Parameters.Select(p => $"{p.ParameterType} {p.ParameterName}"));
        } else {
            // Regelfall: die abstrakte …Logic-Methode wird überschrieben (inkl. Context-Parameter).
            cb.Write($"protected override {transition.Context!.ContextTypeName}.Result {transition.LogicName}(");
            WriteAlignedDecls(cb, LogicSignatureDeclarations(transition));
        }

        cb.Write(") ");
        using (cb.Block()) {
            cb.WriteLine("throw new NotImplementedException();");
        }
    }

    /// <summary>Schreibt den <c>NotImplementedException</c>-Stub der abstrakten <c>{Choice}Logic</c>-Methode (die einmalige Entscheidung, §3.5).</summary>
    static void WriteChoiceStub(CodeBuilder cb, ChoiceCallContextCodeModel choice) {

        cb.Write($"protected override {choice.Context.ContextTypeName}.Result {choice.LogicName}(");
        WriteAlignedDecls(cb, ChoiceLogicDeclarations(choice));

        cb.Write(") ");
        using (cb.Block()) {
            cb.WriteLine("throw new NotImplementedException();");
        }
    }

    /// <summary>Die Parameter-Deklarationen der zu überschreibenden <c>…Logic(…)</c>-Signatur (Transitions-Parameter plus Context-Parameter).</summary>
    static IEnumerable<string> LogicSignatureDeclarations(TransitionCallContextCodeModel transition) {
        return transition.Parameters.Select(p => $"{p.ParameterType} {p.ParameterName}")
                         .Concat(new[] { $"{transition.Context!.ContextTypeName} {CallContextCodeModel.ContextParameterName}" });
    }

    /// <summary>Die Parameter-Deklarationen der zu überschreibenden <c>{Choice}Logic(…)</c>-Signatur (Choice-Parameter plus Context-Parameter).</summary>
    static IEnumerable<string> ChoiceLogicDeclarations(ChoiceCallContextCodeModel choice) {
        return choice.Parameters.Select(p => $"{p.ParameterType} {p.ParameterName}")
                     .Concat(new[] { $"{choice.Context.ContextTypeName} {CallContextCodeModel.ContextParameterName}" });
    }

    /// <summary>Umbrochene, an der öffnenden Klammer ausgerichtete Deklarationsliste (vorformatierte <c>{Typ} {Name}</c>-Strings).</summary>
    static void WriteAlignedDecls(CodeBuilder cb, IEnumerable<string> declarations) {
        cb.WriteAlignedJoin(declarations, d => cb.Write(d), separator: $",{cb.NewLine}");
    }

}
