#region Using Directives

using System.Collections.Generic;
using System.Linq;

#endregion

namespace Pharmatechnik.Nav.Language.CodeGen;

/// <summary>
/// CodeBuilder-Emitter der <c>{Task}WFS</c>-OneShot-Familie der <b>Generation 2</b> — die einmalig
/// erzeugte Benutzer-Datei (<see cref="OverwritePolicy.Never"/>) mit je einem
/// <c>NotImplementedException</c>-Stub für die abstrakten Methoden aus <c>{Task}WFSBase</c>.
/// </summary>
/// <remarks>
/// Anders als V1 überschreiben die Stubs die neuen Logic-Signaturen
/// <c>protected override {Context}.Result …Logic(args, {Context} next)</c> (bzw. bei
/// <c>[abstract]</c>-Quellen die Maschinerie-Methode selbst). Wie die V1-OneShot-Datei trägt sie
/// <b>keinen</b> <c>&lt;auto-generated&gt;</c>-Kopf.
/// </remarks>
static class WfsOneShotEmitterV2 {

    public static string Emit(WfsCodeModelV2 model, CodeGeneratorContext context) {

        var cb = new CodeBuilder();

        // OneShot ist die Benutzer-Datei — kein <auto-generated>-Header.
        EmitterCommon.WriteUsingDirectives(cb, model.UsingNamespaces);

        cb.WriteLine();
        cb.Write($"namespace {model.WflNamespace} ");
        using (cb.Block()) {

            cb.Write($"public partial class {model.WfsTypeName} ");
            using (cb.Block()) {
                WriteMethodStubs(cb, model);
            }
        }

        return cb.ToString();
    }

    static void WriteMethodStubs(CodeBuilder cb, WfsCodeModelV2 model) {

        var transitions = model.InitTransitions
                               .Concat(model.ExitTransitions)
                               .Concat(model.TriggerTransitions)
                               .ToList();

        var wroteAny = false;

        foreach (var transition in transitions) {
            // Jede Methode ist von der vorigen durch genau eine Leerzeile getrennt.
            if (wroteAny) {
                cb.WriteLine();
            }

            WriteStub(cb, transition);
            // Block() schließt mit '}' ohne Zeilenumbruch — die Stub-Zeile hier abschließen.
            cb.WriteLine();
            wroteAny = true;
        }

        // Die {Choice}Logic-Stubs folgen — die Entscheidung, die der Nutzer je Choice EINMAL trifft (§3.5).
        foreach (var choice in model.Choices) {
            if (wroteAny) {
                cb.WriteLine();
            }

            WriteChoiceStub(cb, choice);
            cb.WriteLine();
            wroteAny = true;
        }
    }

    static void WriteStub(CodeBuilder cb, TransitionCallContextCodeModel transition) {

        if (transition.GenerateAbstractMachinery) {
            // [abstract]-Quelle: die Maschinerie-Methode selbst wird überschrieben.
            cb.Write($"{transition.AccessModifier} override {transition.ReturnType} {transition.MachineryName}(");
            WriteAlignedDecls(cb, transition.Parameters.Select(p => $"{p.ParameterType} {p.ParameterName}"));
        } else {
            // Regelfall: die abstrakte …Logic-Methode wird überschrieben (inkl. Context-Parameter).
            cb.Write($"protected override {transition.Context!.ContextTypeName}.Result {transition.LogicName}(");
            WriteAlignedDecls(cb, LogicSignatureDeclarations(transition));
        }

        cb.Write(") ");
        using (cb.Block()) {
            cb.WriteLine("throw new NotImplementedException();");
        }
    }

    static void WriteChoiceStub(CodeBuilder cb, ChoiceCallContextCodeModel choice) {

        cb.Write($"protected override {choice.Context.ContextTypeName}.Result {choice.LogicName}(");
        WriteAlignedDecls(cb, ChoiceLogicDeclarations(choice));

        cb.Write(") ");
        using (cb.Block()) {
            cb.WriteLine("throw new NotImplementedException();");
        }
    }

    static IEnumerable<string> LogicSignatureDeclarations(TransitionCallContextCodeModel transition) {
        return transition.Parameters.Select(p => $"{p.ParameterType} {p.ParameterName}")
                         .Concat(new[] { $"{transition.Context!.ContextTypeName} {CallContextCodeModel.ContextParameterName}" });
    }

    static IEnumerable<string> ChoiceLogicDeclarations(ChoiceCallContextCodeModel choice) {
        return choice.Parameters.Select(p => $"{p.ParameterType} {p.ParameterName}")
                     .Concat(new[] { $"{choice.Context.ContextTypeName} {CallContextCodeModel.ContextParameterName}" });
    }

    static void WriteAlignedDecls(CodeBuilder cb, IEnumerable<string> declarations) {
        cb.WriteAlignedJoin(declarations, d => cb.Write(d), separator: $",{cb.NewLine}");
    }

}
